Resources:
  CognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: "HandTermUserPool"
      Schema:
        - Name: "email"
          Required: true
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true

  CognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - "ALLOW_USER_SRP_AUTH"
        - "ALLOW_REFRESH_TOKEN_AUTH"
      GenerateSecret: false
Outputs:
  UserPoolId:
    Value: !Ref CognitoUserPool
    Description: The ID of the Cognito User Pool
  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
    Description: The ID of the Cognito User Pool Client